services:
  mysql:
    image: mysql:8.0
    ports:
      - "3308:3306"
    restart: always
    container_name: gameapp-database
    volumes:
      - mysql-data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: gameappRoo7t0lk2o20
      MYSQL_DATABASE: gameapp_db
      MYSQL_USER: gameapp
      MYSQL_PASSWORD: gameappt0lk2o20


volumes:
  mysql-data: